### ISSUE TITLE
Support all XMLHttpRequest functionality 

### ISSUE THREAD

**Issue by zzarcon** [devlucky/Kakapo.js#12]
Investigate if we can easily extend all the existing functionalities of `XMLHttpRequest` and just override some methods

**Comment by zzarcon** [comment]
In https://github.com/devlucky/Kakapo.js/blob/master/src/interceptors/xmlhttprequest.js
```javascript
  return class fakeXMLHttpRequest extends nativeXMLHttpRequest{

  }
```

Not sure if this can have some undesired side effects... but could be potentially useful for us 💪 @oskarcieslik

**Comment by oskarcieslik** [comment]
As I remember it's not a good idea to extend XMLHttpRequest because it's a host object and side effects can be bad ;p I think wrapper will be a better idea

**Comment by zzarcon** [comment]
@oskarcieslik you are right, I was trying it before but I just realized that is not a good idea
