### ISSUE TITLE
Response status code

### ISSUE THREAD

**Issue by SAbadi** [devlucky/Kakapo.js#129]
Currently response's status code is hard-coded as 200 and its not possible to change it in a clean way using the current api. 

I was wondering if there is any plan to support response status code other than 200 soon?

**Comment by zzarcon** [comment]
Hi @SAbadi, thanks for the issue, have you tried this?

```javascript
import { Server, Response, Router } from 'kakapo';

const server = new Server();
const router = new Router();

router.get('/users', request => {
  const code = 400;
  const body = {};
  const headers = {};

  return new Response(code, body, headers);
});

server.use(router);
```

Basically you need to use the Kakapo Response class, you can take a look into the docs in here http://devlucky.github.io/kakapo-js#response 

Please let me know if works for you

**Comment by SAbadi** [comment]
Hi @zzarcon ,

Thanks for your prompt response. 

Yes, I have tried that approach as well, but unfortunately it doesn't work. I am using Kakapo version 0.2.0.

You can find the issue in xhrInterceptor.js line 53 and 56. 

So basically whatever route handler returns gets converted to string using JSON.stringify and it will be available only as responseText.

And more importantly in line 56 response's status is set explicitly to 200.

**Comment by zzarcon** [comment]
OMG! You are totally right, I actually thought we had test for such case (which is pretty basic) sorry for pointing you to the docs instead. I'll fix it asap.

Thanks!!

**Comment by zzarcon** [comment]
@SAbadi please let me know if the fix works is working for you

**Comment by SAbadi** [comment]
Hi @zzarcon 

Yes, it is working well now. Thanks for the quick fix.
