### ISSUE TITLE
Abstract fakeXMLHttpRequest & fakeFetch functionality

### ISSUE THREAD

**Issue by oskarcieslik** [devlucky/Kakapo.js#13]
There's some similar functionality in both fakeXMLHttpRequest & fakeFetch, like: reset, saving native function and saving routes. I think we can abstract those three behaviours into some kind of wrapper. What do you think @zzarcon? :)

**Comment by oskarcieslik** [comment]
I believe I must wait with this one for you to fix some issues in #19 :)

**Comment by zzarcon** [comment]
@oskarcieslik actually align it and remove the `path-to-regex`dependency from `xmlhttprequest.js`

**Comment by oskarcieslik** [comment]
@zzarcon k

**Comment by oskarcieslik** [comment]
Closed with #28
