### ISSUE TITLE
this is undefined in onreadystatechange

### ISSUE THREAD

**Issue by huangbinjie** [devlucky/Kakapo.js#134]
When i use this in xhr.onreadystatechange, that cause an error: `Cannot read property 'readyState' of undefined`, here is my error code:
```js
        xhr.onreadystatechange = function xhrReadyStateChange(e) {
            var _a = xhrReadyStateChange, subscriber = _a.subscriber, progressSubscriber = _a.progressSubscriber, request = _a.request;
            if (this.readyState === 4) {
````
it seems that [xhrInterceptor.js#71](https://github.com/devlucky/Kakapo.js/blob/master/src/interceptors/xhrInterceptor.js#L71): `successCallback()` should be `successCallback.call(this)`
please fix it

**Comment by zzarcon** [comment]
@huangbinjie fixed in `0.2.2`, thanks for reporting
