### ISSUE TITLE
Support other environments in interceptors

### ISSUE THREAD

**Issue by rpunkfu** [devlucky/Kakapo.js#15]
Right our interceptors only replace `window.fetch` / `window.XMLHttpRequest`. I think we need to check if framework is used inside of browser, service worker, react native, etc and then assign fake service to `window` / `global` / `self`

**Comment by zzarcon** [comment]
Good point, I was also thinking on give support for Node in the future ;)

**Comment by oskarcieslik** [comment]
Yeah, node is important since that's going to be main environment for running tests with kakapo :)
