### ISSUE TITLE
fetch interceptor assumes all Responses are JSON

### ISSUE THREAD

**Issue by ahixon** [devlucky/Kakapo.js#159]
Fake response will always attempt to serialise to JSON -- see https://github.com/devlucky/Kakapo.js/blob/master/src/interceptors/fetchInterceptor.js#L12

If we want to return, say, a blob of data from a Response, we can never do that. This is useful if you want to return files from mocked endpoints.

Related to, but distinct from, #144

**Comment by zzarcon** [comment]
fixed by @markduke182 !
