### ISSUE TITLE
Intercept requests 

### ISSUE THREAD

**Issue by zzarcon** [devlucky/Kakapo.js#3]
The `Server` class should be able to listen for request on the following implementations:

- [x] Fetch Api
  - [x] Method support: `GET`, `POST`, `PUT`, `DELETE`
  - [x] Headers support
- [x] XMLHttpRequest

Maybe we should consider using a different module for it, something like `Interceptor`? and just isolate there the functionality and integrate in on the `Server`...

**Comment by zzarcon** [comment]
@oskarcieslik a good example of fetch api 

```javascript
var url = 'url';
var headers = new Headers({'X-Custom-Value': 'VALUE'});
var options = {
  method: 'POST',
  headers: headers,
  mode: 'cors',
  cache: 'default'
};
var request = new Request(url);

fetch(request, options)....
```

**Comment by oskarcieslik** [comment]
I believe it's closed already?
