### ISSUE TITLE
Support nested finds

### ISSUE THREAD

**Issue by zzarcon** [devlucky/Kakapo.js#47]
```javascript
const user = db.find('user', {city: {name: 'valencia'}})
```

**Comment by zzarcon** [comment]
@oskarcieslik thoughts?

**Comment by oskarcieslik** [comment]
@zzarcon it's already implemented :)

**Comment by zzarcon** [comment]
lol! can we add some tests for that? :)

**Comment by oskarcieslik** [comment]
Hmmm, I think that we don't support nested properties in factories! Need to implement this ;)

**Comment by oskarcieslik** [comment]
This is working and tested.
