### ISSUE TITLE
Support factories with nested properties

### ISSUE THREAD

**Issue by oskarcieslik** [devlucky/Kakapo.js#49]
Factories like this must work:

```javascript
const userFactory = faker => ({
  name: 'Hector'
  address: {
    zipCode: faker.address.zipCode,
    city: faker.address.city,
    streetName: faker.address.streetName,
  }
});
```

**Comment by zzarcon** [comment]
@devlucky/swift-core Have you thought about this? maybe it's already working for you guys ^^

**Comment by MP0w** [comment]
Yes factory for us are the init and in the init you have to initialize the relationships
