### ISSUE TITLE
Database fake data handling

### ISSUE THREAD

**Issue by zzarcon** [devlucky/Kakapo.js#5]
The `Database` must use https://github.com/Marak/faker.js in order to populate the factory records

Draft...

```javascript
import {DB} from '../src/kakapo';

const db = new DB();
db.register('user', userFactory);

function userFactory(faker) {
  return {
    firstName: faker.name.firstName,
    lastName: 'Zarco',
    avatar: faker.internet.avatar,
    age: 24
  };
}
```

Whenever the DB generate the records it will check the value of the properties, if the value is a function it will execute. That way will can easily define random data

**Comment by oskarcieslik** [comment]
I will take this one now :)
What do you think @zzarcon about my draft:

```javascript
import { Database } from 'kakapo';

const database = new Database();

database.register('user', faker => ({
  firstName: faker.name.firstName,
  lastName: faker.name.lastName,
  avatar: faker.internet.avatar
}), 100); // Generates 100 random records.

const user = database.find('user', {firstName: 'Oskar'}); // Finds users with firstName === 'Oskar'
const users = database.find('user', {}) // Finds all users
const firstUser = database.findById('user', 1); // Finds user by id

user.firstName = 'Hector';
database.save('user', user); // Now user has firstName === 'Hector'

database.remove('user', firstUser); // Now user with id === 1 is removed
```

**Comment by oskarcieslik** [comment]
So I stumbled on this test @zzarcon:

```javascript
db.push('user', userFactory());
```

As you know `userFactory` is used in DB.js, there it's invoked with injected `faker` object, so.... Either we don't support this kind of behaviour ( instead user should use `db.create('user', 1)` ) or support this when user define their own factory without using faker, but that would be making a lot of errors for users who doesn't know what db.js does

**Comment by oskarcieslik** [comment]
For now I won't support it, we need to discuss it first :)

**Comment by oskarcieslik** [comment]
How should we support this @zzarcon:

```javascript
const db = new DB();

db.register('user', userFactory);
db.create('user', 1);
db.push('user', {id: 0, name: 'ICE-T'});

// Now there's two users in store with id: 0...
```

**Comment by MP0w** [comment]
Needs alignement: our implementation forbids multiple entities with the same id (raise an exception) and we avoid it by passing the id that should be used as parameter of the insert closure

**Comment by oskarcieslik** [comment]
@MP0w So it shouldn't be replaced, instead error should be thrown right?

**Comment by MP0w** [comment]
@oskarcieslik either one or the other but we shoukd discuss and align the two libraries. I'm afraid that equal ids might be a programmer mistacke, not sure... Then what's the difference between PUT and PATCH? My initial idea was to forbid same id in insert but having a method to replace the user (immutable in our implementation) to PATCH it

**Comment by oskarcieslik** [comment]
@MP0w I thought about it as a PUT since it replaces the whole record, instead of just assigning new values to existing fields of the record. I think that you're right and pushing record with id that already exists must throw an error. I think it would be nice to have a new method `save` to allow user to make a PATCH operation. Like this:

```javascript
const db = new DB();
db.register('user', userFactory);
db.create('user', 1);

db.push('user', {id: 0, name: 'ICE-T'}); // This throws error
const user = db.findById('user', 0); // Returns copy of the object

console.log(db.findById('user', 0).name) // 'ICE-T'

user.name = 'something new';
db.save('user', user);

console.log(db.findById('user', 0).name) // 'something new'
```

**Comment by MP0w** [comment]
👍 in swift we will use (the user will) immutable structs or classes so you have to create a new user... We need to think about a way to easily do this without replicating all the properties...  but in js you might want to do this or choose what's best for you

**Comment by oskarcieslik** [comment]
@zzarcon, you cool with my suggestion? :)

**Comment by zzarcon** [comment]
I think we should provide this

```javascript
let user = db.findById('user', 0); 

user.name = 'paco';

user.save();
```

**Comment by zzarcon** [comment]
Regarding the potentially `id` conflicts I'll just don't worry about what if the user is passing or not an id as a param in the `push` method, instead **always** set/overwrite the the id inside the `push` method:

```javascript
push(factoryName, content) {
   content.id = this.uuid(factoryName);
   .....
}
```
Otherwise is just adding complexity for free, since in 99% of the cases nobody will create an instance with an specific id, **since is autoincremental** and for this case we will just overwrite the id for the proper one.

**Comment by oskarcieslik** [comment]
@zzarcon yup!
